import { useEffect, useMemo, useState } from 'react'
import { api, patch, post, put, remove } from '../api'
import { Panel } from '../components/Panel'
import { addDays, formatDate, isoDateLocal, startOfWeek } from '../date'
import type { CaseItem, EventItem, Project, Task } from '../types'

type View = 'day' | 'week' | 'month' | 'agenda'
type CalendarItem = { id:string; time?:string; title:string; type:string; kind:'event'|'task'; project_id?:string; project_code?:string; project_title?:string; case_id?:string; case_code?:string; case_title?:string; source:EventItem|Task }
const viewLabels: Record<View,string> = { day:'Giorno', week:'Settimana', month:'Mese', agenda:'Agenda' }
function monthGrid(anchor: Date) { const first=new Date(anchor.getFullYear(),anchor.getMonth(),1,12); return Array.from({length:42},(_,i)=>addDays(startOfWeek(first),i)) }
const EditIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20h4l11-11-4-4L4 16v4zm12-16 4 4 1-1a2 2 0 0 0 0-3l-1-1a2 2 0 0 0-3 0l-1 1z"/></svg>
const DoneIcon=()=> <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg>
const projectHue=(code:string)=>[...code].reduce((sum,char)=>sum+char.charCodeAt(0),0)%360
const ContextMark=({projectCode,projectTitle,caseCode,caseTitle}:{projectCode?:string;projectTitle?:string;caseCode?:string;caseTitle?:string})=>{const code=projectCode||caseCode,title=projectTitle||caseTitle;if(!code)return null;return <span className={`project-mark ${caseCode?'case':''}`} style={{'--project-hue':projectHue(code)} as React.CSSProperties} title={`${caseCode?'Pratica':'Progetto'}: ${title||code}`} aria-label={`${caseCode?'Pratica':'Progetto'} ${title||code}`}>{caseCode?'▤':code.slice(0,2).toUpperCase()}</span>}

export function CalendarPage() {
  const [events,setEvents]=useState<EventItem[]>([]), [tasks,setTasks]=useState<Task[]>([])
  const [projects,setProjects]=useState<Project[]>([])
  const [cases,setCases]=useState<CaseItem[]>([])
  const [view,setView]=useState<View>('agenda'), [anchor,setAnchor]=useState(new Date()), [typeFilter,setTypeFilter]=useState('all')
  const [showForm,setShowForm]=useState(false), [editing,setEditing]=useState<EventItem|null>(null)
  const [title,setTitle]=useState(''), [eventDate,setEventDate]=useState(isoDateLocal()), [startTime,setStartTime]=useState(''), [endTime,setEndTime]=useState('')
  const [location,setLocation]=useState(''), [eventType,setEventType]=useState('personal'), [message,setMessage]=useState('')
  const load=()=>{const start=new Date(anchor.getFullYear(),anchor.getMonth()-1,1,12),end=new Date(anchor.getFullYear(),anchor.getMonth()+2,0,12);return Promise.all([api<EventItem[]>(`/events?start=${isoDateLocal(start)}&end=${isoDateLocal(end)}`).then(setEvents),api<Task[]>('/tasks').then(setTasks),api<Project[]>('/projects').then(setProjects),api<CaseItem[]>('/cases').then(setCases)])}
  useEffect(()=>{void load()},[anchor.getFullYear(),anchor.getMonth()])
  const visibleEvents=useMemo(()=>events.filter(e=>typeFilter==='all'||e.event_type===typeFilter),[events,typeFilter])
  const types=[...new Set(events.map(e=>e.event_type))].sort()
  const itemsFor=(day:string):CalendarItem[]=>[...visibleEvents.filter(e=>e.event_date===day).map(e=>({id:e.id,time:e.start_time?`${e.start_time.slice(0,5)}${e.end_time?`–${e.end_time.slice(0,5)}`:''}`:undefined,title:e.title,type:e.event_type,kind:'event' as const,project_id:e.project_id,project_code:e.project_code,project_title:e.project_title,case_id:e.case_id,case_code:e.case_code,case_title:e.case_title,source:e})),...tasks.filter(t=>t.due_date===day).map(t=>({id:t.id,time:t.due_time?.slice(0,5),title:t.title,type:'task',kind:'task' as const,project_id:t.project_id,project_code:t.project_code,project_title:t.project_title,case_id:t.case_id,case_code:t.case_code,case_title:t.case_title,source:t}))].sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'))
  function move(direction:number){const copy=new Date(anchor);if(view==='day')copy.setDate(copy.getDate()+direction);else if(view==='week'||view==='agenda')copy.setDate(copy.getDate()+7*direction);else copy.setMonth(copy.getMonth()+direction);setAnchor(copy)}
  function openCreate(day?:string){setEditing(null);setTitle('');setEventDate(day||isoDateLocal(anchor));setStartTime('');setEndTime('');setLocation('');setEventType('personal');setShowForm(true);setMessage('')}
  function openEdit(event:EventItem){setEditing(event);setTitle(event.title);setEventDate(event.event_date);setStartTime(event.start_time?.slice(0,5)||'');setEndTime(event.end_time?.slice(0,5)||'');setLocation(event.location||'');setEventType(event.event_type);setShowForm(true);setMessage('')}
  async function save(e:React.FormEvent){e.preventDefault();const payload={title,event_date:eventDate,start_time:startTime||null,end_time:endTime||null,location:location||null,event_type:eventType,project_id:editing?.project_id||null,case_id:editing?.case_id||null,author_profile_id:null,book_id:null};if(editing)await put(`/events/${editing.id}`,payload);else await post('/events',payload);setMessage(`Evento ${editing?'aggiornato':'creato'} il ${formatDate(eventDate)}${startTime?` alle ${startTime}`:''}.`);setShowForm(false);setEditing(null);await load()}
  async function completeItem(item:CalendarItem){await post(`/${item.kind==='event'?'events':'tasks'}/${item.id}/complete`);setMessage(`Completato: ${item.title}`);setShowForm(false);setEditing(null);await load()}
  async function deleteEditing(){if(!editing||!window.confirm(`Eliminare l'evento “${editing.title}”?`))return;await remove(`/events/${editing.id}`);setMessage(`Evento eliminato: ${editing.title}`);setShowForm(false);setEditing(null);await load()}
  async function assignContext(item:CalendarItem,value:string){const isProject=value.startsWith('p:'),isCase=value.startsWith('c:');await patch(`/${item.kind==='event'?'events':'tasks'}/${item.id}/context`,{project_id:isProject?value.slice(2):null,case_id:isCase?value.slice(2):null});setMessage(value?`Collegamento aggiornato per “${item.title}”.`:`Collegamento rimosso da “${item.title}”.`);await load()}
  function selectItem(e:React.MouseEvent,item:CalendarItem){e.stopPropagation();if(item.kind==='event')openEdit(item.source as EventItem)}
  const actions=(item:CalendarItem)=><div className="calendar-item-actions">{item.kind==='event'&&<button type="button" className="icon-action edit" title="Modifica" aria-label={`Modifica ${item.title}`} onClick={e=>selectItem(e,item)}><EditIcon/></button>}<button type="button" className="icon-action done" title="Fatto" aria-label={`Segna come fatto ${item.title}`} onClick={e=>{e.stopPropagation();void completeItem(item)}}><DoneIcon/></button></div>
  const week=Array.from({length:7},(_,i)=>addDays(startOfWeek(anchor),i)),days=view==='day'?[anchor]:week
  const agendaDays=Array.from({length:30},(_,i)=>addDays(anchor,i)).filter(day=>itemsFor(isoDateLocal(day)).length)
  return <div className="stack"><Panel title="Calendario operativo">
    <div className="calendar-toolbar"><div><button onClick={()=>move(-1)}>‹</button><button onClick={()=>setAnchor(new Date())}>Oggi</button><button onClick={()=>move(1)}>›</button></div><strong>{anchor.toLocaleDateString('it-IT',{month:'long',year:'numeric'})}</strong><div className="view-switch">{(Object.keys(viewLabels) as View[]).map(key=><button className={view===key?'active':''} onClick={()=>setView(key)} key={key}>{viewLabels[key]}</button>)}</div></div>
    <div className="calendar-actions"><label>Filtra<select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="all">Tutti</option>{types.map(type=><option key={type} value={type}>{type}</option>)}</select></label><button className="primary" onClick={()=>openCreate()}>＋ Crea evento</button></div>
    {message&&<p className="notice">{message}</p>}
    {showForm&&<form className="event-form" onSubmit={save}><label>Titolo<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Data<input required type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><label>Inizio<input type="time" value={startTime} onChange={e=>setStartTime(e.target.value)}/></label><label>Fine<input type="time" value={endTime} onChange={e=>setEndTime(e.target.value)}/></label><label>Luogo<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Tipo<select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="personal">Personale</option><option value="strategic">Strategico</option><option value="theatre">Teatro</option><option value="deadline">Scadenza</option></select></label><div className="form-buttons">{editing&&<button type="button" className="danger" onClick={deleteEditing}>Elimina</button>}<button type="button" onClick={()=>{setShowForm(false);setEditing(null)}}>Annulla</button>{editing&&<button type="button" className="done" onClick={()=>void completeItem({id:editing.id,title:editing.title,time:editing.start_time,type:editing.event_type,kind:'event',source:editing})}>Fatto</button>}<button className="primary">{editing?'Aggiorna':'Salva evento'}</button></div></form>}
    {view==='month'&&<div className="month-grid"><div className="weekdays">{['Lun','Mar','Mer','Gio','Ven','Sab','Dom'].map((x,i)=><b className={i>4?'weekend':''} key={x}>{x}</b>)}</div>{monthGrid(anchor).map(day=>{const iso=isoDateLocal(day),items=itemsFor(iso),weekend=day.getDay()===0||day.getDay()===6;return <div className={`month-day ${weekend?'weekend':''} ${day.getMonth()!==anchor.getMonth()?'outside':''} ${iso===isoDateLocal()?'today':''}`} key={iso} onClick={()=>openCreate(iso)}><button className="day-number" onClick={()=>openCreate(iso)}>{day.getDate()}</button>{items.slice(0,3).map(item=><div className={`cal-item ${item.kind}`} key={item.kind+item.id} onClick={e=>selectItem(e,item)}><span><ContextMark projectCode={item.project_code} projectTitle={item.project_title} caseCode={item.case_code} caseTitle={item.case_title}/>{item.time&&`${item.time} `}{item.title}</span>{actions(item)}</div>)}{items.length>3&&<em>+{items.length-3}</em>}</div>})}</div>}
    {(view==='day'||view==='week')&&<div className={`calendar-columns ${view}`}>{days.map(day=>{const iso=isoDateLocal(day),items=itemsFor(iso),weekend=day.getDay()===0||day.getDay()===6;return <section className={weekend?'weekend':''} key={iso}><header><strong>{day.toLocaleDateString('it-IT',{weekday:'short',day:'2-digit'})}</strong><small>{formatDate(iso)}</small></header>{items.length===0&&<button className="empty-slot" onClick={()=>openCreate(iso)}>＋ Aggiungi</button>}{items.map(item=><article className={`calendar-event ${item.kind}`} key={item.kind+item.id} onClick={e=>selectItem(e,item)}><time>{item.time||'—'}</time><strong><ContextMark projectCode={item.project_code} projectTitle={item.project_title} caseCode={item.case_code} caseTitle={item.case_title}/>{item.title}</strong><small>{item.type}</small>{actions(item)}</article>)}</section>})}</div>}
    {view==='agenda'&&<div className="timeline">{agendaDays.length===0&&<p>Nessun elemento nei prossimi 30 giorni.</p>}{agendaDays.map(day=>{const iso=isoDateLocal(day);return <section key={iso}><h3>{day.toLocaleDateString('it-IT',{weekday:'long'})} · {formatDate(iso)}</h3>{itemsFor(iso).map(item=><div className="row agenda-row" key={item.kind+item.id}><time>{item.time||'—'}</time><strong><ContextMark projectCode={item.project_code} projectTitle={item.project_title} caseCode={item.case_code} caseTitle={item.case_title}/>{item.title}</strong><select className="project-quick-select" value={item.project_id?`p:${item.project_id}`:item.case_id?`c:${item.case_id}`:''} onClick={e=>e.stopPropagation()} onChange={e=>void assignContext(item,e.target.value)} aria-label={`Collegamento per ${item.title}`}><option value="">Nessun collegamento</option><optgroup label="Progetti">{projects.map(project=><option key={project.id} value={`p:${project.id}`}>{project.title}</option>)}</optgroup><optgroup label="Pratiche">{cases.map(caseItem=><option key={caseItem.id} value={`c:${caseItem.id}`}>{caseItem.title}</option>)}</optgroup></select>{actions(item)}</div>)}</section>})}</div>}
  </Panel></div>
}
