import { useEffect, useState } from 'react'
import './PlanningPage.css'
import { api, post, put } from '../api'
import { Panel } from '../components/Panel'
import { MarkdownView } from '../components/MarkdownView'
import { Status } from '../components/Status'
import { formatDate } from '../date'
import type { Book, CaseItem, Project } from '../types'

type Action = { kind: 'task'|'event'; title: string; reason: string; expected_result: string; date?: string|null; start_time?: string|null; end_time?: string|null; location?: string|null; priority: number; depends_on: number[] }
type Draft = {title:string;explanation:string;assumptions:string[];actions:Action[];start_date:string;end_date:string;target_copies?:number|null;threshold_percent:number;threshold_reason:string;minimum_expected:number;milestones:Array<{date:string;cumulative_copies:number}>}
type Item = {id:string;title:string;status:string;due_date?:string;event_date?:string;completed_at?:string;plan_id?:string}
type Plan = {id:string;case_id?:string;book_id?:string;parent_id?:string;context_title?:string;author_name?:string;status:string;brief:string;revision:number;dialogue:Array<{role:string;content:string}>;draft?:Draft;tasks?:Item[];events?:Item[]}
type Detail = CaseItem & {tasks:Item[];events:Item[]}
type Monitor = {status:string;checkpoint?:string;expected?:number;actual?:number;deviation_percent?:number;message?:string}

export function PlanningPage({initialContext=''}:{initialContext?:string}) {
 const [projects,setProjects]=useState<Project[]>([]),[cases,setCases]=useState<CaseItem[]>([]),[books,setBooks]=useState<Book[]>([])
 const [opened,setOpened]=useState(initialContext),[error,setError]=useState(''),[creating,setCreating]=useState(false)
 const [title,setTitle]=useState(''),[code,setCode]=useState(''),[context,setContext]=useState('')
 const load=()=>Promise.all([api<Project[]>('/projects').then(setProjects),api<CaseItem[]>('/cases').then(setCases),api<Book[]>('/books').then(setBooks)])
 useEffect(()=>{void load().catch(e=>setError((e as Error).message))},[])
 useEffect(()=>{if(initialContext)setOpened(initialContext)},[initialContext])
 if(opened)return <div className="stack"><button className="secondary" onClick={()=>{setOpened('');void load().catch(e=>setError((e as Error).message))}}>‹ Torna a Progetti e Pratiche</button><PlanningDetail key={opened} initialContext={opened}/></div>
 const taskRows=(tasks:Array<{id:string;title:string;due_date?:string}>)=>tasks.map(t=><div className="project-tasks" key={t.id}><strong>{t.title}</strong><small>{t.due_date?formatDate(t.due_date):'Senza data'}</small></div>)
 return <div className="page-grid planning-catalog">{error&&<p className="notice">{error}</p>}
 <Panel title="Progetti" action={<button onClick={()=>window.dispatchEvent(new CustomEvent('second-brain-open-projects'))}>＋ Nuovo</button>}><div className="project-list">{projects.map(p=>{const book=books.find(b=>b.projects.some(project=>project.id===p.id));return <details className="project-card" key={p.id}><summary><span><Status value={p.status}/><strong>{p.title}</strong><small>{p.tasks.length} attività · {p.events?.length||0} eventi</small></span><span className="chevron">⌄</span></summary><div className="project-body"><p>{p.objective}</p>{taskRows(p.tasks)}{book&&<button className="primary" onClick={()=>setOpened('book:'+book.id)}>Apri libro e strategia</button>}</div></details>})}{books.filter(b=>!b.projects.length).map(b=><details className="project-card" key={b.id}><summary><span><Status value={b.status}/><strong>{b.title}</strong><small>{b.author_name}</small></span></summary><div className="project-body"><button onClick={()=>setOpened('book:'+b.id)}>Apri libro e strategia</button></div></details>)}</div></Panel>
 <Panel title="Pratiche" action={<button onClick={()=>setCreating(v=>!v)}>＋ Nuova</button>}>{creating&&<form onSubmit={e=>{e.preventDefault();setError('');void post<CaseItem>('/planning/cases',{title,code,context_markdown:context}).then(c=>{setCreating(false);setOpened('case:'+c.id)}).catch(err=>setError((err as Error).message))}}><label>Codice<input required value={code} onChange={e=>setCode(e.target.value)}/></label><label>Titolo<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Situazione e obiettivo<textarea rows={4} value={context} onChange={e=>setContext(e.target.value)}/></label><button>Crea pratica</button></form>}<div className="project-list">{cases.map(c=><details className="project-card case-card" key={c.id}><summary><span><Status value={c.status}/><strong>{c.title}</strong><small>{c.tasks?.length||0} attività · {c.events?.length||0} eventi</small></span><span className="chevron">⌄</span></summary><div className="project-body"><p>{c.context_markdown}</p>{taskRows(c.tasks||[])}<button className="primary" onClick={()=>setOpened('case:'+c.id)}>Apri pratica</button></div></details>)}</div></Panel>
 </div>
}

function PlanningDetail({initialContext}:{initialContext:string}) {
 const [cases,setCases]=useState<CaseItem[]>([]),[books,setBooks]=useState<Book[]>([]),[plans,setPlans]=useState<Plan[]>([])
 const [selected,setSelected]=useState(''),[caseDetail,setCaseDetail]=useState<Detail|null>(null),[plan,setPlan]=useState<Plan|null>(null)
 const [brief,setBrief]=useState(''),[reply,setReply]=useState(''),[draftText,setDraftText]=useState(''),[monitor,setMonitor]=useState<Monitor|null>(null)
 const [newTitle,setNewTitle]=useState(''),[newCode,setNewCode]=useState(''),[newContext,setNewContext]=useState('')
 const [title,setTitle]=useState(''),[code,setCode]=useState(''),[context,setContext]=useState('')
 const [manualTitle,setManualTitle]=useState(''),[kind,setKind]=useState<'task'|'event'>('task'),[day,setDay]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[location,setLocation]=useState(''),[coverage,setCoverage]=useState('')
 const [error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=async()=>{const [c,b,p]=await Promise.all([api<CaseItem[]>('/cases'),api<Book[]>('/books'),api<Plan[]>('/planning/plans')]);setCases(c);setBooks(b);setPlans(p)}
 useEffect(()=>{void load().then(()=>select(initialContext)).catch(e=>setError(String(e)))},[])
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const showPlan=(p:Plan)=>{setPlan(p);setDraftText(p.draft?JSON.stringify(p.draft,null,2):'');setMonitor(null)}
 const refreshCase=async(id:string)=>{const d=await api<Detail>(`/planning/cases/${id}`);setCaseDetail(d);setTitle(d.title);setCode(d.code);setContext(d.context_markdown)}
 const select=async(value:string)=>{setSelected(value);setCaseDetail(null);setPlan(null);setMonitor(null);setBrief('');if(value.startsWith('case:'))await refreshCase(value.slice(5))}
 const createCase=()=>run(async()=>{const c=await post<CaseItem>('/planning/cases',{code:newCode,title:newTitle,context_markdown:newContext});setNewCode('');setNewTitle('');setNewContext('');await load();await select('case:'+c.id)})
 const createPlan=()=>run(async()=>{const [type,id]=selected.split(':');const p=await post<Plan>('/planning/plans',{brief,case_id:type==='case'?id:null,book_id:type==='book'?id:null});showPlan(p);await load();showPlan(await post<Plan>(`/planning/plans/${p.id}/interview`,{text:'Leggi il contesto e fammi le domande necessarie prima di proporre il piano.',revision:p.revision}));await load()})
 const operation=(action:string)=>run(async()=>{if(!plan)return;const p=await post<Plan>(`/planning/plans/${plan.id}/${action}`,{revision:plan.revision});showPlan(p);await load();if(caseDetail)await refreshCase(caseDetail.id)})
 const draftEdit:Draft|null=draftText?JSON.parse(draftText):null
 const editDraft=(update:(d:Draft)=>Draft)=>{if(draftEdit)setDraftText(JSON.stringify(update(structuredClone(draftEdit)),null,2))}
 const editAction=(index:number,changes:Partial<Action>)=>editDraft(d=>({...d,actions:d.actions.map((a,i)=>i===index?{...a,...changes}:a)}))
 const saveDraft=()=>run(async()=>{if(!plan)return;const p=await put<Plan>(`/planning/plans/${plan.id}/draft`,{revision:plan.revision,draft:JSON.parse(draftText)});showPlan(p);await load()})
 const manual=()=>run(async()=>{if(!caseDetail)return;const common={title:manualTitle};await post(`/planning/cases/${caseDetail.id}/${kind==='task'?'tasks':'events'}`,kind==='task'?{...common,due_date:day||null,due_time:start||null,priority:3}:{...common,event_date:day,start_time:start||null,end_time:end||null,location:location||null,event_type:'personal'});setManualTitle('');setDay('');setStart('');setEnd('');setLocation('');await refreshCase(caseDetail.id);await load()})
 const items=(entries:Item[])=>entries.map(i=><div className="row" key={i.id}><div><strong>{i.title}</strong><small>{i.due_date||i.event_date||'Senza data'} · {i.status} · {i.plan_id?'Piano agente':'Manuale'}{i.completed_at?` · completata ${i.completed_at}`:''}</small></div>{!['completed','cancelled'].includes(i.status)&&<button disabled={busy} onClick={()=>void run(async()=>{await post(`/${i.event_date?'events':'tasks'}/${i.id}/complete`);if(caseDetail)await refreshCase(caseDetail.id);if(plan)showPlan(await api<Plan>(`/planning/plans/${plan.id}`))})}>Fatto</button>}</div>)
 useEffect(()=>{if(!plan||plan.status!=='active'||!plan.book_id||plan.parent_id)return;let cancelled=false;const check=()=>api<Monitor>(`/planning/plans/${plan.id}/monitor`).then(m=>{if(!cancelled)setMonitor(m)}).catch(e=>{if(!cancelled)setError((e as Error).message)});void check();const timer=window.setInterval(()=>void check(),60000);return()=>{cancelled=true;window.clearInterval(timer)}},[plan?.id,plan?.status])
 const labels:Record<string,string>={data_missing:'Dati da aggiornare',insufficient_history:'In attesa di dati sufficienti',below_threshold:'Scostamento oltre soglia',in_line:'In linea'}
 const editable=plan&&['interview','draft'].includes(plan.status)
 return <div className="page-grid planning-page">
  {error&&<p className="notice" role="alert">{error}</p>}
  <Panel title={caseDetail?.title||books.find(b=>b.id===selected.slice(5))?.title||'Dettaglio'}><select hidden value={selected} disabled={busy} onChange={e=>void run(()=>select(e.target.value))}><option value="">Seleziona…</option><optgroup label="Libri">{books.map(b=><option key={b.id} value={'book:'+b.id}>{b.title} · {b.author_name}</option>)}</optgroup><optgroup label="Pratiche">{cases.map(c=><option key={c.id} value={'case:'+c.id}>{c.title}</option>)}</optgroup></select>
   <details hidden><summary>Nuova pratica</summary><label>Codice<input value={newCode} onChange={e=>setNewCode(e.target.value)}/></label><label>Titolo<input value={newTitle} onChange={e=>setNewTitle(e.target.value)}/></label><label>Situazione e obiettivo<textarea rows={6} value={newContext} onChange={e=>setNewContext(e.target.value)}/></label><button disabled={busy||!newCode||!newTitle} onClick={createCase}>Crea pratica</button></details>
   {caseDetail&&<><h3>Contesto della pratica</h3><label>Titolo<input value={title} onChange={e=>setTitle(e.target.value)}/></label><textarea rows={6} value={context} onChange={e=>setContext(e.target.value)}/><button disabled={busy} onClick={()=>void run(async()=>{await put(`/planning/cases/${caseDetail.id}`,{code,title,context_markdown:context});await refreshCase(caseDetail.id);await load()})}>Salva contesto</button>
   <h3>Aggiungi manualmente</h3><select value={kind} onChange={e=>setKind(e.target.value as 'task'|'event')}><option value="task">TODO</option><option value="event">Evento</option></select><label>Titolo<input value={manualTitle} onChange={e=>setManualTitle(e.target.value)}/></label><label>Data {kind==='task'?'(facoltativa)':''}<input type="date" value={day} onChange={e=>setDay(e.target.value)}/></label><label>Ora<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label>{kind==='event'&&<><label>Fine<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Luogo<input value={location} onChange={e=>setLocation(e.target.value)}/></label></>}<button disabled={busy||!manualTitle||(kind==='event'&&!day)||Boolean(start&&!day)} onClick={manual}>Aggiungi {kind==='task'?'TODO':'evento'}</button>
   <h3>Attività aperte</h3>{items([...caseDetail.tasks,...caseDetail.events].filter(i=>!['completed','cancelled'].includes(i.status)))}<details><summary>Storico completate e annullate</summary>{items([...caseDetail.tasks,...caseDetail.events].filter(i=>['completed','cancelled'].includes(i.status)))}</details></>}
   {selected&&<><h3>Nuovo piano / strategia</h3><textarea rows={5} value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Obiettivo, periodo o quarter, target, budget e vincoli. Per ricominciare inserisci le istruzioni aggiornate."/><button disabled={busy||!brief} onClick={createPlan}>Avvia bozza</button></>}
  </Panel>
  <Panel title="Piani e strategie"><div className="list">{plans.filter(p=>!selected||p.case_id===selected.slice(5)||p.book_id===selected.slice(5)).map(p=><button disabled={busy} className="secondary" key={p.id} onClick={()=>void run(async()=>showPlan(await api<Plan>(`/planning/plans/${p.id}`)))}>{p.context_title} {p.author_name?`· ${p.author_name}`:''} · {p.status}{p.parent_id?' · Correzione':''}</button>)}</div>
   {plan&&<><h3>{plan.draft?.title||'Colloquio'} · {plan.status}</h3><p>{plan.brief}</p>{plan.dialogue.map((turn,i)=><div key={i}><strong>{turn.role==='user'?'Tu':'Agente'}</strong><MarkdownView value={turn.content}/></div>)}
   {editable&&<><textarea rows={3} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Rispondi alle domande o chiedi di chiarire il caso"/><button disabled={busy||!reply} onClick={()=>void run(async()=>{const p=await post<Plan>(`/planning/plans/${plan.id}/interview`,{text:reply,revision:plan.revision});showPlan(p);setReply('');await load()})}>Invia all’agente</button><button disabled={busy||!plan.dialogue.length} onClick={()=>operation('generate')}>Genera / rigenera bozza</button><button disabled={busy} onClick={()=>operation('discard')}>Scarta bozza</button></>}
   {plan.draft&&<><MarkdownView value={plan.draft.explanation}/><h4>Ipotesi da verificare</h4><ul>{plan.draft.assumptions.map((a,i)=><li key={i}>{a}</li>)}</ul><p>Periodo: {plan.draft.start_date} — {plan.draft.end_date}. Target: {plan.draft.target_copies??'personale'}. Soglia: {plan.draft.threshold_percent}% · {plan.draft.threshold_reason}</p>{plan.draft.actions.map((a,i)=><article className="row" key={i}><div><strong>{i+1}. {a.title}</strong><small>{a.date||'Senza data'} · {a.kind==='task'?'TODO':'Evento'}</small><p>{a.reason}</p><p>Risultato atteso: {a.expected_result||'Da verificare'}</p>{a.depends_on.length>0&&<small>Prerequisiti: azioni {a.depends_on.map(n=>n+1).join(', ')}</small>}</div></article>)}
   {editable&&<><details><summary>Modifica bozza</summary>{draftEdit&&<>
<label>Titolo<input value={draftEdit.title} onChange={e=>editDraft(d=>({...d,title:e.target.value}))}/></label>
<label>Spiegazione<textarea rows={4} value={draftEdit.explanation} onChange={e=>editDraft(d=>({...d,explanation:e.target.value}))}/></label>
<label>Inizio<input type="date" value={draftEdit.start_date} onChange={e=>editDraft(d=>({...d,start_date:e.target.value}))}/></label>
<label>Fine<input type="date" value={draftEdit.end_date} onChange={e=>editDraft(d=>({...d,end_date:e.target.value}))}/></label>
{plan.book_id&&!plan.parent_id&&<label>Target copie<input type="number" min="1" value={draftEdit.target_copies??''} onChange={e=>editDraft(d=>({...d,target_copies:e.target.value?Number(e.target.value):null}))}/></label>}
<label>Soglia di scostamento (%)<input type="number" min="1" max="100" value={draftEdit.threshold_percent} onChange={e=>editDraft(d=>({...d,threshold_percent:Number(e.target.value)}))}/></label>
<label>Motivazione della soglia<textarea value={draftEdit.threshold_reason} onChange={e=>editDraft(d=>({...d,threshold_reason:e.target.value}))}/></label>
<label>Copie attese minime prima del controllo<input type="number" min="1" value={draftEdit.minimum_expected} onChange={e=>editDraft(d=>({...d,minimum_expected:Number(e.target.value)}))}/></label>
<label>Ipotesi da verificare (una per riga)<textarea value={draftEdit.assumptions.join('\n')} onChange={e=>editDraft(d=>({...d,assumptions:e.target.value.split('\n')}))}/></label>
{draftEdit.actions.map((a,i)=><fieldset key={i}><legend>Azione {i+1}</legend>
<label>Tipo<select value={a.kind} onChange={e=>editAction(i,{kind:e.target.value as 'task'|'event'})}><option value="task">TODO</option><option value="event">Evento</option></select></label>
<label>Titolo<input value={a.title} onChange={e=>editAction(i,{title:e.target.value})}/></label>
<label>Perché<textarea value={a.reason} onChange={e=>editAction(i,{reason:e.target.value})}/></label>
<label>Risultato atteso<input value={a.expected_result} onChange={e=>editAction(i,{expected_result:e.target.value})}/></label>
<label>Data<input type="date" value={a.date||''} onChange={e=>editAction(i,{date:e.target.value||null})}/></label>
<label>Ora<input type="time" value={a.start_time||''} onChange={e=>editAction(i,{start_time:e.target.value||null})}/></label>
{a.kind==='event'&&<><label>Fine<input type="time" value={a.end_time||''} onChange={e=>editAction(i,{end_time:e.target.value||null})}/></label><label>Luogo<input value={a.location||''} onChange={e=>editAction(i,{location:e.target.value||null})}/></label></>}
<label>Priorità<select value={a.priority} onChange={e=>editAction(i,{priority:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}</option>)}</select></label>
<label>Azioni da svolgere prima (numeri separati da virgola)<input value={a.depends_on.map(n=>n+1).join(',')} onChange={e=>editAction(i,{depends_on:e.target.value?e.target.value.split(',').map(n=>Number(n.trim())-1):[]})}/></label>
<button disabled={busy} onClick={()=>editDraft(d=>({...d,actions:d.actions.filter((_,n)=>n!==i).map(x=>({...x,depends_on:x.depends_on.filter(n=>n!==i).map(n=>n>i?n-1:n)}))}))}>Rimuovi azione</button>
</fieldset>)}
<button disabled={busy} onClick={()=>editDraft(d=>({...d,actions:[...d.actions,{kind:'task',title:'',reason:'',expected_result:'',date:null,start_time:null,end_time:null,location:null,priority:3,depends_on:[]}]}))}>Aggiungi azione proposta</button>
{plan.book_id&&<><h4>Aspettative cumulative di vendita</h4>{draftEdit.milestones.map((m,i)=><div key={i} className="planning-checkpoint"><label>Data<input type="date" value={m.date} onChange={e=>editDraft(d=>({...d,milestones:d.milestones.map((v,n)=>n===i?{...v,date:e.target.value}:v)}))}/></label><label>Copie totali attese<input type="number" min="0" value={m.cumulative_copies} onChange={e=>editDraft(d=>({...d,milestones:d.milestones.map((v,n)=>n===i?{...v,cumulative_copies:Number(e.target.value)}:v)}))}/></label><button disabled={busy} onClick={()=>editDraft(d=>({...d,milestones:d.milestones.filter((_,n)=>n!==i)}))}>Rimuovi checkpoint</button></div>)}<button disabled={busy} onClick={()=>editDraft(d=>({...d,milestones:[...d.milestones,{date:d.end_date,cumulative_copies:d.target_copies||0}]}))}>Aggiungi checkpoint</button></>}
</>}<p>Salva le modifiche prima di approvare. Le attività proposte non sono ancora nel calendario.</p><button disabled={busy} onClick={saveDraft}>Salva modifiche</button></details><button disabled={busy||draftText!==JSON.stringify(plan.draft,null,2)} onClick={()=>operation('approve')}>Approva esplicitamente e calendarizza</button></>}
   </>}
   {plan.status==='active'&&<><button disabled={busy} className="danger" onClick={()=>{if(window.confirm('Annullare tutte le attività aperte di questo piano e delle sue correzioni? Le completate e gli elementi manuali restano nello storico.'))void operation('clean')}}>Pulisci piano completamente</button><h4>Attività e storico del piano</h4>{items([...(plan.tasks||[]),...(plan.events||[])])}
   {plan.book_id&&!plan.parent_id&&<><h4>Controllo vendite</h4><label>Dati completi fino al (anche zero vendite)<input type="date" value={coverage} onChange={e=>setCoverage(e.target.value)}/></label><button disabled={busy||!coverage} onClick={()=>void run(async()=>setMonitor(await post<Monitor>(`/planning/plans/${plan.id}/coverage`,{through:coverage})))}>Conferma dati e controlla</button><button disabled={busy} onClick={()=>void run(async()=>setMonitor(await api<Monitor>(`/planning/plans/${plan.id}/monitor`)))}>Controlla andamento</button>{monitor&&<><p>{labels[monitor.status]||monitor.status} · {monitor.message||`Attese ${monitor.expected}, vendute ${monitor.actual}, scostamento ${monitor.deviation_percent?.toFixed(1)??'—'}% al ${monitor.checkpoint}`}</p>{monitor.status==='below_threshold'&&<button disabled={busy} onClick={()=>void run(async()=>{showPlan(await post<Plan>(`/planning/plans/${plan.id}/correction`));await load()})}>Apri proposta di correzione</button>}</>}</>}
   </>}
   {['discarded','cleaned'].includes(plan.status)&&<button disabled={busy} onClick={()=>operation('regenerate')}>Ricomincia con una nuova bozza</button>}
   {busy&&<p role="status">Elaborazione in corso…</p>}</>}
  </Panel>
 </div>
}
