import { useEffect, useState } from 'react'
import { api, post } from '../api'
import { Panel } from '../components/Panel'
import { Status } from '../components/Status'
import { formatDate } from '../date'
import type { CaseItem, Profile, Project } from '../types'

export function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>([])
  const [cases, setCases] = useState<CaseItem[]>([])
  const [profiles,setProfiles]=useState<Profile[]>([])
  const [showForm,setShowForm]=useState(false),[kind,setKind]=useState<'project'|'book'>('project')
  const [code,setCode]=useState(''),[title,setTitle]=useState(''),[objective,setObjective]=useState(''),[authorCode,setAuthorCode]=useState(''),[publicationDate,setPublicationDate]=useState(''),[message,setMessage]=useState('')
  const load=()=>Promise.all([api<Project[]>('/projects').then(setProjects),api<CaseItem[]>('/cases').then(setCases)])
  useEffect(() => { void load();api<Profile[]>('/profiles').then(setProfiles) }, [])
  async function createProject(e:React.FormEvent){e.preventDefault();setMessage('');await post('/projects',{kind,code,title,objective:objective||null,author_code:authorCode||null,publication_date:kind==='book'&&publicationDate?publicationDate:null});setMessage(kind==='book'?'Libro e progetto creati.':'Progetto creato.');setCode('');setTitle('');setObjective('');setPublicationDate('');setShowForm(false);await load()}
  return <div className="page-grid">
    <Panel title="Progetti" action={<button className="primary" onClick={()=>setShowForm(value=>!value)}>＋ Nuovo</button>}>
      {message&&<p className="notice">{message}</p>}
      {showForm&&<form className="project-create-form" onSubmit={createProject}><label>Tipo<select value={kind} onChange={e=>setKind(e.target.value as 'project'|'book')}><option value="project">Progetto generale</option><option value="book">Nuovo libro</option></select></label><label>Codice<input required pattern="[A-Za-z0-9_-]+" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="NUOVO_LIBRO"/></label><label>Titolo<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Autore<select required={kind==='book'} value={authorCode} onChange={e=>setAuthorCode(e.target.value)}><option value="">Nessun autore</option>{profiles.map(profile=><option key={profile.id} value={profile.code}>{profile.display_name}</option>)}</select></label>{kind==='book'&&<label>Pubblicazione prevista<input type="date" value={publicationDate} onChange={e=>setPublicationDate(e.target.value)}/></label>}<label className="wide">Obiettivo<textarea rows={2} value={objective} onChange={e=>setObjective(e.target.value)} placeholder="Risultato che vuoi ottenere"/></label><div className="form-buttons wide"><button type="button" onClick={()=>setShowForm(false)}>Annulla</button><button className="primary">Crea</button></div></form>}
      <div className="project-list">{projects.map(p => <details className="project-card" key={p.id}><summary><span><Status value={p.status}/><strong>{p.title}</strong><small>{p.tasks.length} attività · {p.events?.length||0} eventi</small></span><span className="chevron">⌄</span></summary><div className="project-body"><p>{p.objective}</p>{(p.author_name||p.book_title)&&<small>{p.author_name}{p.book_title ? ` · ${p.book_title}` : ''}</small>}<h4>Attività collegate</h4>{p.tasks.length===0?<p className="empty-project">Nessuna attività aperta.</p>:<div className="project-tasks">{p.tasks.map(task=><div key={task.id}><span className="task-dot"/><strong>{task.title}</strong><small>{task.due_date?formatDate(task.due_date):'Senza data'}{task.due_time?` · ${task.due_time.slice(0,5)}`:''}</small></div>)}</div>}<h4>Eventi collegati</h4>{!p.events?.length?<p className="empty-project">Nessun evento futuro.</p>:<div className="project-tasks">{p.events.map(event=><div key={event.id}><span className="event-dot"/><strong>{event.title}</strong><small>{formatDate(event.event_date)}{event.start_time?` · ${event.start_time.slice(0,5)}`:''}</small></div>)}</div>}</div></details>)}</div>
    </Panel>
    <Panel title="Pratiche"><div className="project-list">{cases.map(c => <details className="project-card case-card" key={c.id}><summary><span><Status value={c.status}/><strong>{c.title}</strong><small>{c.tasks?.length||0} attività · {c.events?.length||0} eventi</small></span><span className="chevron">⌄</span></summary><div className="project-body"><p>{c.context_markdown}</p><h4>Attività collegate</h4>{!c.tasks?.length?<p className="empty-project">Nessuna attività aperta.</p>:<div className="project-tasks">{c.tasks.map(task=><div key={task.id}><span className="task-dot"/><strong>{task.title}</strong><small>{task.due_date?formatDate(task.due_date):'Senza data'}{task.due_time?` · ${task.due_time.slice(0,5)}`:''}</small></div>)}</div>}<h4>Eventi collegati</h4>{!c.events?.length?<p className="empty-project">Nessun evento futuro.</p>:<div className="project-tasks">{c.events.map(event=><div key={event.id}><span className="event-dot"/><strong>{event.title}</strong><small>{formatDate(event.event_date)}{event.start_time?` · ${event.start_time.slice(0,5)}`:''}</small></div>)}</div>}</div></details>)}</div></Panel>
  </div>
}
