import { useEffect, useState } from 'react'
import { api, post, remove } from '../api'
import { Panel } from '../components/Panel'
import { formatDate } from '../date'
type Action={id:string;title:string;date?:string;time?:string;kind:string}
type Card={id:string;title:string;kind:'book'|'case';status?:string;completed:number;total:number;overdue:number;actions:Action[];strategies:{id:string;title:string;next_review_date?:string}[];plans:{id:string;status:string;brief:string;draft?:{title:string;target_copies?:number}}[];sales?:{month:number;previous:number;last_sale?:string};monitoring?:{status:string;message?:string;expected?:number;actual?:number;target?:number}[]}
type Data={date:string;cards:Card[];strategies_active:number;plans_active:number}
export function WorkDashboard(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function load(){setError('');try{setData(await api<Data>('/work/overview'))}catch(e){setError((e as Error).message)}}
 useEffect(()=>{void load()},[])
 async function chat(c:Card){setBusy(true);setError('');try{const x=await post<{id:string}>(`/work/${c.kind}/${c.id}/conversation`);window.dispatchEvent(new CustomEvent('second-brain-open-chat',{detail:x.id}))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function close(c:Card){if(!window.confirm('Chiudere la pratica? La conversazione sarà archiviata e le attività aperte annullate. Lo storico sarà conservato.'))return;setBusy(true);try{await post(`/work/cases/${c.id}/close`);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const labels:Record<string,string>={data_missing:'Dati di vendita da confermare',insufficient_history:'In attesa del primo checkpoint',below_threshold:'Sotto le aspettative',on_track:'In linea'}
 const attention=data?.cards.flatMap(c=>[...(c.overdue?[`${c.title}: ${c.overdue} attività/eventi scaduti`]:[]),...c.strategies.filter(s=>s.next_review_date&&s.next_review_date<=data.date).map(s=>`${c.title}: revisione di ${s.title}`),...(c.monitoring||[]).filter(m=>['data_missing','below_threshold'].includes(m.status)).map(m=>`${c.title}: ${labels[m.status]}`)])||[]
 const end=data?new Date(data.date+'T12:00:00'):new Date();end.setDate(end.getDate()+6);const until=end.toISOString().slice(0,10)
 const upcoming=data?.cards.flatMap(c=>c.actions.filter(a=>a.date&&a.date>=data.date&&a.date<=until).map(a=>({...a,context:c.title}))).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.time||'').localeCompare(b.time||''))||[]
 return <div className="stack work-dashboard"><Panel title="Il mio centro operativo" action={<button disabled={busy} onClick={()=>void load()}>Aggiorna</button>}><p>Libri sotto strategia e pratiche aperte, insieme.</p>{error&&<p role="alert" className="notice error">{error}</p>}{!data&&!error&&<p>Caricamento…</p>}{data&&<div className="work-metrics"><strong>{data.cards.filter(c=>c.kind==='book').length} libri monitorati</strong><strong>{data.cards.filter(c=>c.kind==='case').length} pratiche aperte</strong><strong>{data.strategies_active} strategie editoriali</strong><strong>{data.plans_active} piani attivi</strong><small>Dati al {formatDate(data.date)}</small></div>}</Panel>
 {data&&<><Panel title="Richiedono attenzione">{attention.length?<ul>{attention.map((a,i)=><li key={i}>{a}</li>)}</ul>:<p>Nessuna criticità rilevata nei dati disponibili.</p>}</Panel><div className="work-cards">{data.cards.map(c=><Panel key={c.kind+c.id} title={c.title}><small>{c.kind==='book'?'Libro sotto strategia':'Pratica aperta'}</small>{c.sales&&<><h3>{c.sales.month} copie registrate nel mese</h3><p>Mese precedente: {c.sales.previous} copie (mese completo).</p><small>Vendite da confermare: l’assenza di registrazioni non dimostra zero vendite.</small></>}{c.strategies.map(s=><p key={s.id}><strong>{s.title}</strong>{s.next_review_date&&<> · Revisione: {formatDate(s.next_review_date)}</>}</p>)}{c.plans.map(p=><p key={p.id}>{p.draft?.title||p.brief} · {p.status==='active'?'Attivo':'Bozza'}{p.draft?.target_copies?` · Obiettivo ${p.draft.target_copies} copie`:''}</p>)}{c.monitoring?.map((m,i)=><p key={i}>{labels[m.status]||m.status}: {m.message||`Attese ${m.expected??'—'}, vendute ${m.actual??'—'}`}</p>)}{c.kind==='book'&&!c.monitoring?.length&&<p>Monitoraggio vendite rispetto al target: apri la strategia per i dettagli. Nessuna valutazione automatica senza un piano con checkpoint.</p>}<p>{c.completed}/{c.total} attività ed eventi completati · {c.overdue} scaduti</p><h4>Prossima azione aperta</h4>{c.actions[0]?<p>{c.actions[0].title} · {c.actions[0].date?formatDate(c.actions[0].date):'Senza data'}</p>:<p>Nessuna azione aperta.</p>}<div className="form-buttons"><button disabled={busy} className="primary" onClick={()=>void chat(c)}>Parla di questo lavoro</button><button onClick={()=>window.dispatchEvent(new CustomEvent('second-brain-open-context',{detail:c.kind+':'+c.id}))}>Apri dettagli</button>{c.kind==='case'&&<button disabled={busy} onClick={()=>void close(c)}>Chiudi pratica</button>}</div></Panel>)}</div>{!data.cards.length&&<p>Nessun libro con strategia attiva o pratica aperta.</p>}<Panel title="Prossimi sette giorni">{upcoming.length?<div className="list">{upcoming.map(a=><p key={a.kind+a.id}><strong>{a.context}</strong> · {formatDate(a.date!)} {a.time?.slice(0,5)} · {a.title}</p>)}</div>:<p>Nessuna azione pianificata.</p>}</Panel><ClosedCases onChange={load}/></>}
 </div>
}
function ClosedCases({onChange}:{onChange:()=>Promise<void>}){
 const [items,setItems]=useState<{id:string;title:string;status:string}[]>([]),[error,setError]=useState('')
 async function load(){try{setItems((await api<typeof items>('/cases')).filter(c=>['closed','completed','cancelled','archived'].includes(c.status)))}catch(e){setError((e as Error).message)}}
 return <details><summary onClick={()=>void load()}>Pratiche chiuse e storico</summary>{error&&<p role="alert">{error}</p>}{items.map(c=><p key={c.id}>{c.title} <button onClick={()=>window.dispatchEvent(new CustomEvent('second-brain-open-context',{detail:'case:'+c.id}))}>Storico</button> <button className="danger" onClick={async()=>{if(!window.confirm(`Eliminare definitivamente ${c.title}, conversazione, piani, attività ed eventi collegati? Operazione irreversibile.`))return;try{await remove(`/work/cases/${c.id}?confirm=true`);await load();await onChange()}catch(e){setError((e as Error).message)}}}>Elimina definitivamente</button></p>)}</details>
}
